image:
  repository: strm/helloworld-http
  pullPolicy: IfNotPresent
  tag: latest

serviceAccount:
  create: true
  annotations: {}

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80      # also containerPort in deployment.yaml

ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts:
    - host: shop-backend-api.flaschenpost.services
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 50m
    memory: 128Mi
  requests:
    cpu: 20m
    memory: 64Mi

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  tcpSocket:
    port: 80
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /index.html
    port: 80
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 3

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

cronjob:
  name: hello-sre
  schedule: "*/30 * * * *"
  image: busybox
  args:
    - /bin/sh
    - -c
    - echo "Hello SRE"
  restartPolicy: OnFailure

nodeSelector: {}

tolerations: []

affinity: {}
